apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: dev
type: Opaque
stringData:
  DATABASE_URL: postgres://postgres:postgres@postgres-statefulset-0.postgres-service.dev.svc.cluster.local:5432/postgres?sslmode=disable
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
