apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: panchanandevops/golang-mux-app:v1.0.0
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
            requests:
              memory: "64Mi"
              cpu: "100m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  namespace: dev
spec:
  selector:
    app: go-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
