apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.secret.name }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.stringData.DATABASE_URL }}
  POSTGRES_DB: {{ .Values.secret.stringData.POSTGRES_DB }}
  POSTGRES_USER: {{ .Values.secret.stringData.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secret.stringData.POSTGRES_PASSWORD }}
